sudo: false

language: python

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

cache:
  directories:
    - ~/.cache/pip

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

python:
  - 2.7
  - 3.4
  - 3.5

before_install:
  - pip install pip setuptools --upgrade

install:
  - CC=g++-4.8 pip install .\[test\] --upgrade

script:
  - py.test test ais --cov ais --cov-report term-missing
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then (cd src && CC=gcc-4.8 CXX=g++-4.8 make -f Makefile-custom test); fi
