sudo: false
dist: trusty

language: python

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

cache:
  directories:
    - ~/.cache/pip

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

python:
  - 2.7
  - 3.5

before_install:
  - pip install pip setuptools --upgrade
  - pip install pip pytest --upgrade

install:
  - CC=g++-7 pip install .\[tests\] --upgrade

script:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then (cd src && CC=gcc-7 CXX=g++-7 make -f Makefile-custom -j 4 test); fi
  - py.test ais test --cov=ais --cov-report term-missing
